### ISSUE TITLE
Update Lecture 7: Classification

### ISSUE THREAD

**Issue by melsigl** [FAU-CS6/KDD#6]
**Definition of Done**
All sections updated, as well as reviewed with incorporated feedback.

**Tasks**
- [x] Read chapter 8 of book 
- [x] Update section "Decision-Tree"
- [x] Update section "Bayes Classification"
- [x] Update section "Rule-Based Classification"
- [x] Update section "Model Evaluation & Selection"
- [x] Update section "Ensemble Methods"
- [x] Reviewed
