### ISSUE TITLE
Update Lecture 9: Outlier

### ISSUE THREAD

**Issue by melsigl** [FAU-CS6/KDD#8]
**Definition of Done**
All sections updated, as well as reviewed with incorporated feedback.

**Tasks**
- [x] Read chapter 12 of book 
- [x] Update section "Outlier and Outlier Analysis
- [x] Update section "Outlier-Detection Methods
- [x] Update section "Statistical Approaches"
- [x] Update section "Proximity-Based  Approaches
- [x] Update section "Summary"
- [x] Reviewed
